name: Run Action
on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run the action
        id: memoryinfo
        uses: ./
      - name: output
        run: |
          echo ${{ steps.memoryinfo.outputs.memory }}
          echo "total memory successfully output"
